# Simulator configuration parameters
  /bicycle_sim/dt: 0.001                   # Integration step

# Vehicle parameters
  /bicycle_sim/L: 0.26                     # Vehicle length

# Vehicle initial state
  /bicycle_sim/x0: 0.0                     # Initial position x
  /bicycle_sim/y0: 0.0                     # Initial position y
  /bicycle_sim/theta0: 0.0                 # Initial heading

